#ifndef _ERR_H
#define _ERR_H


typedef enum {
  Err_OK = 0, // Err_OK vs Err_NIL
  Err_COMM_INIT,
  Err_COMM_FINAL,
  Err_COMM_NUM_OF_PROCS,
  Err_COMM_PROC_ID,
  Err_COMM_RECEIVE,
  Err_COMM_SEND,
  Err_COMM_TAG,
  Err_INST_EXEC,
  Err_INST_UNKNOWN,
  Err_MEMORY_ALLOC,
  Err_MEMORY_OUT_OF_RANGE,
  Err_MESSAGE_TAG,
  Err_PROGRAM_FILE,
  Err_PROGRAM_SYMBOL,
  Err_PROGRAM_WORDSIZE,
  //Err_PROGRAM_ENDIANNESS,
  Err_SIGNAL_UNKNOWN,
} Err;


#endif
