#ifndef ERROR_H_
#define ERROR_H_


typedef enum {
  Error_OK = 0,
  Error_NETWORK_INITIALIZE,
  Error_NETWORK_FINALIZE,
  Error_NETWORK_NUM_OF_PROCESSORS,
  Error_NETWORK_PROCESSOR_ID,
  Error_NETWORK_RECEIVE,
  Error_NETWORK_SEND,
  Error_COMMAND_ARGS,
  Error_INSTRUCTION_EXECUTE,
  Error_INSTRUCTION_UNKNOWN,
  Error_MEMORY_ALLOC,
  Error_MEMORY_OUT_OF_RANGE,
  Error_MESSAGE_UNKNOWN_TAG,
  Error_PROGRAM_FILE,
  Error_PROGRAM_SYMBOL,
  Error_PROGRAM_WORDSIZE,
  //Error_PROGRAM_ENDIANNESS,
  Error_SIGNAL_UNKNOWN,
} Error;


#endif
