#ifndef S9_ERROR_H_
#define S9_ERROR_H_


typedef enum {
  S9_OK,
  S9_ERROR_COMMAND_ARGS,
  S9_ERROR_INSTRUCTION_EXECUTE,
  S9_ERROR_MEMORY_ALLOC,
  S9_ERROR_MEMORY_OUT_OF_RANGE,
  S9_ERROR_NETWORK_FINALIZE,
  S9_ERROR_NETWORK_INITIALIZE,
  S9_ERROR_NETWORK_RECEIVE,
  S9_ERROR_NETWORK_SEND_SIGNAL,
  S9_ERROR_NETWORK_SEND_TOKEN,
  S9_ERROR_OPCODE_UNKNOWN,
  S9_ERROR_PROGRAM_SIZE,
  //S9_ERROR_PROGRAM_SYMBOL,
  //S9_ERROR_PROGRAM_WORDSIZE,
  //S9_ERROR_PROGRAM_ENDIANNESS,
  S9_ERROR_SIGNAL_UNKNOWN,
} s9_error_t;


#endif // S9_ERROR_H_
